### ISSUE TITLE
[Doc] Tutorial 03 - HPS for ML (Advanced) 

### ISSUE THREAD

**Issue by jke513** [deephyper/deephyper#102] opened 2021-08-09 01:12 UTC
**Describe the bug**
deephyper hps ambs --problem dh_project.rf_tuning.problem.Problem --run dh_project.rf_tuning.model_run.run --max-evals 10 --evaluator subprocess --n-jobs 4
or 
 deephyper hps ambs --evaluator ray --num-workers 2 --max-evals 10 --problem dh_project.polynome2.problem.Problem --run dh_project.polynome2.model_run.run

deephyper hps ambs --problem deephyper.sklearn.classifier.Problem --run dh_project.autoclassifier.model_run.run --max-evals 10 --num-workers 2

deephyper hps ambs --problem deephyper.sklearn.regressor.Problem --run dh_project.autoregressor.model_run.run --max-evals 10 --num-workers 2

print out empty lists? 

 *******************************************************************************
   Maximizing the return value of function: dh_project.rf_tuning.model_run.run
 *******************************************************************************
Already evaluated points:
[]
[]

**To Reproduce**
deephyper hps ambs --problem dh_project.rf_tuning.problem.Problem --run dh_project.rf_tuning.model_run.run --max-evals 10 --evaluator subprocess --n-jobs 4
or 
 deephyper hps ambs --evaluator ray --num-workers 2 --max-evals 10 --problem dh_project.polynome2.problem.Problem --run dh_project.polynome2.model_run.run

deephyper hps ambs --problem deephyper.sklearn.classifier.Problem --run dh_project.autoclassifier.model_run.run --max-evals 10 --num-workers 2

**Expected behavior**
Not sure if it is expected. 

**Screenshots**
![Screen Shot 2021-08-08 at 8 11 15 PM](https://user-images.githubusercontent.com/13974130/128651735-5e3488db-20d0-4cb1-825b-db17cdffef00.png)

**Desktop (please complete the following information):**
 - OS: macos
 - System:  MacBook pro
 - Python version 3.8
 - DeepHyper Version 2.0.5

**Additional context**

**Comment by Deathn0t** [comment] 2021-08-09 11:23
duplicate of #94 , these print statements are not expected and reflect some debug statements that were not deleted. Thanks for reporting.

**Closed by Deathn0t** 2021-08-09 11:23 UTC
Labels: question, docs
