### ISSUE TITLE
[Doc] Tutorial 01 - HPS for ML (Basic) 

### ISSUE THREAD

**Issue by jke513** [deephyper/deephyper#101] opened 2021-08-09 00:30 UTC
**Describe the bug**
benchmark airplane. 

The expected output is:
[Out]
X_train shape: (10000, 7)
y_train shape: (10000,)
X_valid shape: (119258, 7)
y_valid shape: (119258,)

different from what I have 
(deephyper) ➜  rf_tuning (develop) ✗ python load_data.py
X_train shape: (242128, 7)
y_train shape: (242128,)
X_valid shape: (119258, 7)
y_valid shape: (119258,)

**To Reproduce**
![Screen Shot 2021-08-08 at 7 31 42 PM](https://user-images.githubusercontent.com/13974130/128650481-61b81fc7-e3eb-48d3-9807-628d84b0c3b2.png)

(deephyper) ➜  rf_tuning (develop) ✗ python load_data.py
X_train shape: (242128, 7)
y_train shape: (242128,)
X_valid shape: (119258, 7)
y_valid shape: (119258,)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - System: MacBook pro
 - Python version [e.g. 3.8]
 - DeepHyper Version 0.2.5 dev

**Additional context**

**Comment by Deathn0t** [comment] 2021-08-09 11:26
duplicate of #95 and fixed.

**Closed by Deathn0t** 2021-08-09 11:26 UTC
Labels: docs
